version: '3.8'

name: 'structura'

services:
  consul:
    image: hashicorp/consul:1.14
    container_name: consul
    restart: unless-stopped
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - consul:/consul/data
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    networks:
      - structura-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8008:8080"
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8008
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    networks:
      - structura-network

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: structura
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - structura-network

  elasticsearch:
    build: ./elasticsearch # Build từ Dockerfile bạn vừa tạo ở trên
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Quan trọng: Giới hạn RAM
      - xpack.security.enabled=false   # Quan trọng: Tắt security cho dễ dev
      - bootstrap.memory_lock=true     # Khuyến nghị bởi ES
    ulimits: # Khuyến nghị bởi ES
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - structura-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4 # Dùng cùng version với ES ở Dockerfile
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - structura-network
    depends_on:
      - elasticsearch

volumes:
  consul:
    driver: local
  elasticsearch_data:
  postgres_data:

networks:
  structura-network:
    name: structura-network
    driver: bridge