INSERT INTO warehouses (created_at, created_by, updated_at, updated_by, version, warehouse_address, warehouse_name, partner_id) VALUES
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô A5, KCN Sóng Thần 1, TP. Dĩ An, Bình Dương', 'Kho Thép Hòa Hưng (Bình Dương)', 1),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường số 6, KCN Biên Hòa 2, TP. Biên Hòa, Đồng Nai', 'Kho Vật tư Việt Phát (Biên Hòa)', 2),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Bãi xe số 3, Cảng Cát Lái, TP. Thủ Đức, TP.HCM', 'Kho bãi Huy Lan Express (Cát Lái)', 3),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô C10, KCN Hòa Khánh, Q. Liên Chiểu, Đà Nẵng', 'Kho Thép Miền Trung (Đà Nẵng)', 4),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường N2, KCN Mỹ Phước 2, TX. Bến Cát, Bình Dương', 'Kho Vật tư Xây lắp Việt Tùng', 5),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Gần Cảng Phú Hữu, TP. Thủ Đức, TP.HCM', 'Kho trung chuyển Cường Trang Logistics', 6),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô B7, KCN Nhơn Trạch 1, H. Nhơn Trạch, Đồng Nai', 'Kho thành phẩm Nam Hạnh Steel', 7),
(NOW(), 'system_init', NOW(), 'system_init', 0, '156 Xa lộ Hà Nội, P. An Phú, TP. Thủ Đức, TP.HCM', 'Kho Kết Cấu Thép Công Ánh (An Phú)', 8),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường số 9, KCN Tân Bình, Q. Tân Phú, TP.HCM', 'Kho hàng Thắng Hồng (Tân Bình)', 9),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô D1, KCN Long Thành, H. Long Thành, Đồng Nai', 'Tổng kho Phân Phối Thép Tuấn Hà', 10),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Tạ Quang Bửu, P.5, Q.8, TP.HCM', 'Kho Vật liệu Xây dựng Long Nhi (Quận 8)', 11),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực Depot Sóng Thần, TP. Dĩ An, Bình Dương', 'Bãi tập kết Container Sơn Kim', 12),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô F4, KCN Amata, TP. Biên Hòa, Đồng Nai', 'Kho Thép Xây Dựng Bình Tâm (Amata)', 13),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường số 12, KCN Lê Minh Xuân, H. Bình Chánh, TP.HCM', 'Kho thành phẩm Cơ khí Hoàng Dung', 14),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Gần Ngã tư Vũng Tàu, TP. Biên Hòa, Đồng Nai', 'Kho bãi xe Phúc Liên', 15),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô E2, KCN Hiệp Phước, H. Nhà Bè, TP.HCM', 'Kho Thép Công Nghiệp Phong Hải', 16),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường D2, KCN VSIP II, TP. Thủ Dầu Một, Bình Dương', 'Kho Vật tư Hạ tầng Quang Minh', 17),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Cảng PTSC, TP. Vũng Tàu, Bà Rịa - Vũng Tàu', 'Kho hàng Siêu Trường Siêu Trọng Nhật Nguyên (Vũng Tàu)', 18),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô G9, KCN Mỹ Phước 1, TX. Bến Cát, Bình Dương', 'Kho Thép Ống Bảo Linh', 19),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Nguyễn Văn Linh, Q. Long Biên, Hà Nội', 'Kho Liên Doanh Thép Long Nguyệt (Hà Nội)', 20),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực Cảng Lotus, Q.7, TP.HCM', 'Kho Logistics Khải Chi (Quận 7)', 21),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô H3, KCN Sóng Thần 3, TP. Thủ Dầu Một, Bình Dương', 'Kho Thép Hình Tú Hà', 22),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường số 10, KCN Tân Tạo, Q. Bình Tân, TP.HCM', 'Xưởng Gia Công Kết Cấu Phúc Thủy (Tân Tạo)', 23),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Bãi Container ICD Tân Cảng Long Bình, Đồng Nai', 'Kho bãi Vận Tải Huy Phương (Long Bình)', 24),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô I6, KCN Tân Đông Hiệp B, TP. Dĩ An, Bình Dương', 'Kho Nhà Máy Thép Tấm Bình Linh', 25),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Hoàng Quốc Việt, P. Phú Mỹ, Q.7, TP.HCM', 'Kho Vật tư Xây Dựng Dũng Giang (Quận 7)', 26),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Gần KCN Biên Hòa 1, TP. Biên Hòa, Đồng Nai', 'Kho Giao Nhận Hàng Nặng Tiến Chi', 27),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô K2, KCN Long Hậu, H. Cần Giuộc, Long An', 'Tổng Kho Thép Miền Nam Huy Châu (Long Hậu)', 28),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Vành Đai Trong, P. Bình Trị Đông B, Q. Bình Tân, TP.HCM', 'Kho Thương Mại Thép Nhân Hằng (Bình Tân)', 29),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực Ga Sóng Thần, TP. Dĩ An, Bình Dương', 'Kho bãi Đường Sắt Phong Vy', 30),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô M4, KCN Tân Thới Hiệp, Q.12, TP.HCM', 'Kho Thép Không Gỉ Việt Trang', 31),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Huỳnh Tấn Phát, H. Nhà Bè, TP.HCM', 'Kho Dự Án Bảo Hạnh (Nhà Bè)', 32),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực Cảng Bến Nghé, Q.7, TP.HCM', 'Kho Logistics Minh Quỳnh (Bến Nghé)', 33),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô N7, KCN Tân Tạo Mở Rộng, H. Bình Chánh, TP.HCM', 'Kho Thép Đặc Chủng Duy Thy', 34),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Nguyễn Hữu Thọ, P. Phước Kiển, H. Nhà Bè, TP.HCM', 'Kho Xây Lắp Công Nghiệp Hiếu Thảo', 35),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Bãi xe An Sương, Q.12, TP.HCM', 'Kho Hàng Dự Án Quân Diệp (An Sương)', 36),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô P1, KCN VSIP 1, TP. Thuận An, Bình Dương', 'Kho Thép Mạ Kẽm Trí Kim', 37),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Bùi Văn Hòa, P. Long Bình, TP. Biên Hòa, Đồng Nai', 'Kho Thương Mại Hưng My Steel', 38),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực Cầu Đồng Nai, TP. Biên Hòa, Đồng Nai', 'Kho Vận Tải Container Thành Nguyệt', 39),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô Q5, KCN Sóng Thần 2, TP. Dĩ An, Bình Dương', 'Kho Đại Lý Thép Vũ My', 40),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường số 2, KCN Vĩnh Lộc, H. Bình Chánh, TP.HCM', 'Kho Đầu Tư Xây Dựng Khiêm Lam', 41),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Gần ICD Sotrans, TP. Thủ Đức, TP.HCM', 'Kho Vận Tải Hàng Nặng Hùng Thu', 42),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô R2, KCN Amata, TP. Biên Hòa, Đồng Nai', 'Kho Thép Thái Nga (Amata)', 43),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Hoàng Diệu 2, P. Linh Trung, TP. Thủ Đức, TP.HCM', 'Kho Kỹ Thuật Kết Cấu Trường Ngọc', 44),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Bãi xe Miền Đông Mới, TP. Thủ Đức, TP.HCM', 'Kho Giao Nhận Kiệt Ngân (Miền Đông)', 45),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô S8, KCN Tân Phú Trung, H. Củ Chi, TP.HCM', 'Kho Vật Tư Thép Sơn My', 46),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường số 7, KCN Hiệp Phước, H. Nhà Bè, TP.HCM', 'Kho Tập đoàn Thép Trí Thủy', 47),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực cảng Bến Đầm, Côn Đảo, Bà Rịa - Vũng Tàu', 'Kho Vận Tải Siêu Tốc Hiếu Anh (Côn Đảo)', 48),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô T1, KCN Mỹ Phước 3, TX. Bến Cát, Bình Dương', 'Kho Thép Phúc Chi (Mỹ Phước)', 49),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Võ Văn Kiệt, P. An Lạc, Q. Bình Tân, TP.HCM', 'Kho Xây Dựng Khánh Dương (Bình Tân)', 50),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Gần KCN Cát Lái II, TP. Thủ Đức, TP.HCM', 'Kho Logistics Lộc Nhàn Trans (Cát Lái)', 51),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô U3, KCN Nhơn Trạch 3, H. Nhơn Trạch, Đồng Nai', 'Kho Thép Tấm Đạt Thy', 52),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Huỳnh Tấn Phát, Q.7, TP.HCM', 'Kho Thương Mại Thép An Oanh (Quận 7)', 53),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực Kho Box Sotrans, TP. Thủ Đức, TP.HCM', 'Kho Giao Hàng Thép Khoa Trâm', 54),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô V6, KCN Tân Đông Hiệp A, TP. Dĩ An, Bình Dương', 'Kho Thép Cán Nóng Trung Trang', 55),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Nguyễn Văn Tạo, KCN Long Hậu, Long An', 'Kho Nhà Xưởng Phát Linh (Long Hậu)', 56),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Gần KCN Pou Yuen, Q. Bình Tân, TP.HCM', 'Kho Vận Tải Thép Trung Nhi (Bình Tân)', 57),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô W1, KCN Sóng Thần 1, TP. Dĩ An, Bình Dương', 'Kho Phân Phối Thép Khôi Vân (Sóng Thần)', 58),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường số 3, KCN Biên Hòa 1, TP. Biên Hòa, Đồng Nai', 'Kho Tư Vấn Xây Dựng Toàn Mai', 59),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Bãi xe Tam Bình, TP. Thủ Đức, TP.HCM', 'Kho Xe Cẩu Huy Nhung (Tam Bình)', 60),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô X4, KCN Hiệp Phước, H. Nhà Bè, TP.HCM', 'Kho Thép Hợp Kim Anh Phương', 61),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường D4, KCN VSIP II Mở Rộng, Tân Uyên, Bình Dương', 'Kho Đầu Tư Thép Khoa Thu (VSIP II MR)', 62),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực Cảng Cái Mép, TX. Phú Mỹ, Bà Rịa - Vũng Tàu', 'Kho Vận Tải Đường Biển Tú Dương (Cái Mép)', 63),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô Y9, KCN Mỹ Phước 2, TX. Bến Cát, Bình Dương', 'Kho Thép Hình Hưng Nga', 64),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Nguyễn Xiển, P. Long Thạnh Mỹ, TP. Thủ Đức, TP.HCM', 'Kho Kết Cấu Thép Danh Vy (Quận 9 cũ)', 65),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Gần Cảng Bến Lức, H. Bến Lức, Long An', 'Kho Freight Thuận Ngọc (Bến Lức)', 66),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô Z2, KCN Nhơn Trạch 5, H. Nhơn Trạch, Đồng Nai', 'Kho Thép Ống Đúc Phong Hạ', 67),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường ĐT 743, P. An Phú, TP. Thuận An, Bình Dương', 'Kho Xây Dựng Cầu Đường Quang Lệ', 68),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực Chợ đầu mối Hóc Môn, TP.HCM', 'Kho bãi Vận Tải Tài Giang (Hóc Môn)', 69),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô A11, KCN Phú Mỹ 1, TX. Phú Mỹ, Bà Rịa - Vũng Tàu', 'Kho Thép Việt Đức Phúc Bích (Phú Mỹ)', 70),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường số 5, KCN Tân Tạo, Q. Bình Tân, TP.HCM', 'Kho Thương Mại Tân Ngân', 71),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Bãi xe Hoàng Hữu Nam, TP. Thủ Đức, TP.HCM', 'Kho Vận Chuyển Thép Minh Vân (Quận 9 cũ)', 72),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô B15, KCN Biên Hòa 2, TP. Biên Hòa, Đồng Nai', 'Kho Tổng Kho Thép Hải Tuyến (Biên Hòa)', 73),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường số 1, KCN Sóng Thần 3, TP. Thủ Dầu Một, Bình Dương', 'Kho Cơ Khí Chính Xác Đăng Âu', 74),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực Cảng Long Bình Tân, Đồng Nai', 'Kho Vận Tải Container Vinh Huyền', 75),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô C18, KCN Amata, TP. Biên Hòa, Đồng Nai', 'Kho Tín Tú Steel (Amata)', 76),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Nguyễn Duy Trinh, P. Phú Hữu, TP. Thủ Đức, TP.HCM', 'Kho Nam Lan Construction (Phú Hữu)', 77),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực Ngã Ba Thái Lan, Quốc lộ 51, Đồng Nai', 'Kho Xe Tải Lợi Nhung (QL51)', 78),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô D22, KCN Tân Đông Hiệp B, TP. Dĩ An, Bình Dương', 'Kho Thép Tâm Hoa (Dĩ An)', 79),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Lê Văn Việt, P. Tăng Nhơn Phú A, TP. Thủ Đức, TP.HCM', 'Kho Xây Dựng Giao Thông Vinh Trang', 80),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Bãi xe Suối Tiên, TP. Thủ Đức, TP.HCM', 'Kho Vận Chuyển Hàng Khắc Minh (Suối Tiên)', 81),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô E25, KCN Nhơn Trạch 6, H. Nhơn Trạch, Đồng Nai', 'Kho Sản Xuất Thép Tín Quỳnh', 82),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường số 8, KCN Vĩnh Lộc, H. Bình Chánh, TP.HCM', 'Kho Thương Mại Thép Tài Yến', 83),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực ICD Phước Long, TP. Thủ Đức, TP.HCM', 'Kho Vũ My Logistics (Phước Long)', 84),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô F28, KCN Tân Tạo, Q. Bình Tân, TP.HCM', 'Kho Sắt Thép Khôi Châu', 85),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Gò Dưa, P. Tam Bình, TP. Thủ Đức, TP.HCM', 'Kho Xây Lắp Long Chi (Tam Bình)', 86),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Gần KCN Tân Bình, Q. Tân Phú, TP.HCM', 'Kho Vận Tải Tâm Thảo (Tân Bình)', 87),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô G30, KCN Amata, TP. Biên Hòa, Đồng Nai', 'Kho Thép Dũng Mai (Amata)', 88),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Đỗ Xuân Hợp, P. Phước Long B, TP. Thủ Đức, TP.HCM', 'Kho Trung Anh Engineering (Quận 9 cũ)', 89),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Bãi xe Cầu Vượt Linh Xuân, TP. Thủ Đức, TP.HCM', 'Kho Giao Nhận Hiếu Thủy (Linh Xuân)', 90),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô H33, KCN Sóng Thần 1, TP. Dĩ An, Bình Dương', 'Kho Vật Tư Xây Dựng Minh Hà (Sóng Thần)', 91),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường Nguyễn Xiển, P. Long Bình, TP. Thủ Đức, TP.HCM', 'Kho Tập đoàn Hùng Châu (Long Bình)', 92),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực Cảng Đồng Nai, TP. Biên Hòa, Đồng Nai', 'Kho Vận Tải Hải Hằng (Cảng Đồng Nai)', 93),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô I36, KCN Tân Đông Hiệp A, TP. Dĩ An, Bình Dương', 'Kho Thép Tuấn Phương (Dĩ An)', 94),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường N1, KCN Lê Minh Xuân 3, H. Bình Chánh, TP.HCM', 'Kho Cơ Khí Duy Thúy (Lê Minh Xuân 3)', 95),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Bãi xe ngã tư Ga, Q.12, TP.HCM', 'Kho Logistics Việt Ngân Trans (Ngã Tư Ga)', 96),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô K39, KCN Nhơn Trạch 1, H. Nhơn Trạch, Đồng Nai', 'Kho Thép Hưng Trúc (Nhơn Trạch)', 97),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Đường số 4, KCN Tân Tạo, Q. Bình Tân, TP.HCM', 'Kho Thương Mại Dũng Nga Steel (Tân Tạo)', 98),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Khu vực cầu Phú Mỹ, Q.7, TP.HCM', 'Kho Giao Hàng Kiên Liên (Phú Mỹ)', 99),
(NOW(), 'system_init', NOW(), 'system_init', 0, 'Lô L42, KCN Biên Hòa 2, TP. Biên Hòa, Đồng Nai', 'Kho Thép Khang Vân (Biên Hòa)', 100);
