server:
  port: 8000

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8008/realms/structura
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 30s
        fail-fast: false
        prefer-ip-address: true
        query-passing: true
    gateway:
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/api/demo/**
          filters:
            - RewritePath=/api/demo, /core-service/demo
            - RewritePath=/api/demo/(?<segment>.*), /core-service/demo/$\{segment}
#        - id: keycloak
#          uri: ${KEYCLOAK_URL}
#          predicates:
#            - Path=/api/auth/sign-in, /api/auth/token
#          filters:
#            - SetPath=/realms/hometopia/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  zipkin:
#    tracing:
#      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
        cloud:
          gateway: TRACE
